server:
  port: 8080
spring:
  application:
    name: shiro-admin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/shiro_admin?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      ################## 连接池配置 ################
      #连接池建立时创建的初始化连接数
      initial-size: 5
      #连接池中最大的活跃连接数
      max-active: 20
      #连接池中最小的活跃连接数
      min-idle: 5
      # 配置获取连接等待超时的时间
      max-wait: 60000
      max-pool-prepared-statement-per-connection-size: 20
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      validation-query: SELECT 1 FROM DUAL
      query-timeout: 30000
      #是否在获得连接后检测其可用性
      test-on-borrow: false
      #是否在连接放回连接池后检测其可用性
      test-on-return: false
      #是否在连接空闲一段时间后检测其可用性
      test-while-idle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
      #设置监控页面的登录名和密码
      stat-view-servlet:
        login-username: admin
        login-password: 666666
  redis:
    host: localhost
    password: root
    port: 6379
    # 连接超时时间（10秒）
    timeout: PT10S
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 1024
        # 连接池最大阻塞等待时间（使用负值表示没有限制）10秒
        max-wait: PT10S
        # 连接池中的最大空闲连接
        max-idle: 200
        # 连接池中的最小空闲连接
        min-idle: 0
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml

logging:
  #  path: logs
  #  file: ${logging.path}/${spring.application.name}.log
  level:
    root: error
    com.zzk.shiroadmin: debug

swagger:
  enable: true

#JWT 密钥
jwt:
  secretKey: 78944878877848fg)
  accessTokenExpireTime: PT2H
  refreshTokenExpireTime: PT8H
  refreshTokenExpireAppTime: P30D
  issuer: zzk